name: Run bash script kitsunebi/genRules.sh at 4 AM
on:
  workflow_dispatch:
  schedule:
    # Runs every day at 4 AM
    - cron: '0 4 * * *'

jobs:
  run-script-kitsunebi-genrule:
    # runs-on: ubuntu-latest
    runs-on: HOME_VM_UBUNTU
    steps:
      - uses: actions/checkout@v2 # Checks out your repository

      - name: kitsunebi genrule
        shell: bash
        run: |
          cd kitsunebi
          ./genRules.sh update
          test $? && echo "exit with $?" && exit $?
          ./genRules.sh kitsunebi
          test -z $(git diff kitsunebi_blacklist.conf) && echo "No Update" && exit 0
          git add kitsunebi_blacklist.conf
          git add gfwlist.txt
          git add gfwlist_dec.txt
          git commit -m "Github Action: update kitsunebi rules at [$(LANG=C date)]" || exit 0
          git push origin master
